const april = require("../core-index.js");
const Enum = require("../../enum.js");

// Prices are based on network so prices are list as 0
let PricingTable = [
  {
    _id: april.pricingTables.Core.WorldwideExcludingUSA,
    plan: april.plans.Core,
    annualLimit: [{ currency: Enum.currency.USD, value: 200000 }],
    startDate: "2023-03-01T00:00:00.000Z",
    endDate: "",
    includedResidence: ["AE-AJ", "AE-FU", "AE-SH", "AE-RK", "AE-UQ", "AE-DU"],
    excludedResidence: ["AE-AZ"],
    coverage: [april.coverages.WorldwideExcludingUSA],
    baseAnnualPremium: [
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.male,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.female,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
    ],
  },
  {
    _id: april.pricingTables.EssentialIPOrOP.WorldwideIncludingUSA,
    plan: april.plans.EssentialIPOrOP,
    annualLimit: [{ currency: Enum.currency.USD, value: 1000000 }],
    startDate: "2023-03-01T00:00:00.000Z",
    endDate: "",
    includedResidence: ["AE-AJ", "AE-FU", "AE-SH", "AE-RK", "AE-UQ", "AE-DU"],
    excludedResidence: ["AE-AZ"],
    coverage: [april.coverages.WorldwideIncludingUSA],
    baseAnnualPremium: [
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.male,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.female,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
    ],
  },
  {
    _id: april.pricingTables.EssentialIPOrOP.WorldwideExcludingUSA,
    plan: april.plans.EssentialIPOrOP,
    annualLimit: [{ currency: Enum.currency.USD, value: 1000000 }],
    startDate: "2023-03-01T00:00:00.000Z",
    endDate: "",
    includedResidence: ["AE-AJ", "AE-FU", "AE-SH", "AE-RK", "AE-UQ", "AE-DU"],
    excludedResidence: ["AE-AZ"],
    coverage: [april.coverages.WorldwideExcludingUSA],
    baseAnnualPremium: [
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.male,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.female,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
    ],
  },
  {
    _id: april.pricingTables.EssentialIPOrExtensiveOP.WorldwideIncludingUSA,
    plan: april.plans.EssentialIPOrExtensiveOP,
    annualLimit: [{ currency: Enum.currency.USD, value: 1000000 }],
    startDate: "2023-03-01T00:00:00.000Z",
    endDate: "",
    includedResidence: ["AE-AJ", "AE-FU", "AE-SH", "AE-RK", "AE-UQ", "AE-DU"],
    excludedResidence: ["AE-AZ"],
    coverage: [april.coverages.WorldwideIncludingUSA],
    baseAnnualPremium: [
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.male,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.female,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
    ],
  },
  {
    _id: april.pricingTables.EssentialIPOrExtensiveOP.WorldwideExcludingUSA,
    plan: april.plans.EssentialIPOrExtensiveOP,
    annualLimit: [{ currency: Enum.currency.USD, value: 1000000 }],
    startDate: "2023-03-01T00:00:00.000Z",
    endDate: "",
    includedResidence: ["AE-AJ", "AE-FU", "AE-SH", "AE-RK", "AE-UQ", "AE-DU"],
    excludedResidence: ["AE-AZ"],
    coverage: [april.coverages.WorldwideExcludingUSA],
    baseAnnualPremium: [
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.male,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.female,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
    ],
  },
  {
    _id: april.pricingTables.EssentialIPOrEliteOP.WorldwideIncludingUSA,
    plan: april.plans.EssentialIPOrEliteOP,
    annualLimit: [{ currency: Enum.currency.USD, value: 1000000 }],
    startDate: "2023-03-01T00:00:00.000Z",
    endDate: "",
    includedResidence: ["AE-AJ", "AE-FU", "AE-SH", "AE-RK", "AE-UQ", "AE-DU"],
    excludedResidence: ["AE-AZ"],
    coverage: [april.coverages.WorldwideIncludingUSA],
    baseAnnualPremium: [
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.male,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.female,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
    ],
  },
  {
    _id: april.pricingTables.EssentialIPOrEliteOP.WorldwideExcludingUSA,
    plan: april.plans.EssentialIPOrEliteOP,
    annualLimit: [{ currency: Enum.currency.USD, value: 1000000 }],
    startDate: "2023-03-01T00:00:00.000Z",
    endDate: "",
    includedResidence: ["AE-AJ", "AE-FU", "AE-SH", "AE-RK", "AE-UQ", "AE-DU"],
    excludedResidence: ["AE-AZ"],
    coverage: [april.coverages.WorldwideExcludingUSA],
    baseAnnualPremium: [
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.male,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.female,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
    ],
  },
  {
    _id: april.pricingTables.ExtensiveIPOrOP.WorldwideIncludingUSA,
    plan: april.plans.ExtensiveIPOrOP,
    annualLimit: [{ currency: Enum.currency.USD, value: 2500000 }],
    startDate: "2023-03-01T00:00:00.000Z",
    endDate: "",
    includedResidence: ["AE-AJ", "AE-FU", "AE-SH", "AE-RK", "AE-UQ", "AE-DU"],
    excludedResidence: ["AE-AZ"],
    coverage: [april.coverages.WorldwideIncludingUSA],
    baseAnnualPremium: [
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.male,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.female,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
    ],
  },
  {
    _id: april.pricingTables.ExtensiveIPOrOP.WorldwideExcludingUSA,
    plan: april.plans.ExtensiveIPOrOP,
    annualLimit: [{ currency: Enum.currency.USD, value: 2500000 }],
    startDate: "2023-03-01T00:00:00.000Z",
    endDate: "",
    includedResidence: ["AE-AJ", "AE-FU", "AE-SH", "AE-RK", "AE-UQ", "AE-DU"],
    excludedResidence: ["AE-AZ"],
    coverage: [april.coverages.WorldwideExcludingUSA],
    baseAnnualPremium: [
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.male,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.female,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
    ],
  },
  {
    _id: april.pricingTables.ExtensiveIPOrEssentialOP.WorldwideIncludingUSA,
    plan: april.plans.ExtensiveIPOrEssentialOP,
    annualLimit: [{ currency: Enum.currency.USD, value: 2500000 }],
    startDate: "2023-03-01T00:00:00.000Z",
    endDate: "",
    includedResidence: ["AE-AJ", "AE-FU", "AE-SH", "AE-RK", "AE-UQ", "AE-DU"],
    excludedResidence: ["AE-AZ"],
    coverage: [april.coverages.WorldwideIncludingUSA],
    baseAnnualPremium: [
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.male,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.female,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
    ],
  },
  {
    _id: april.pricingTables.ExtensiveIPOrEssentialOP.WorldwideExcludingUSA,
    plan: april.plans.ExtensiveIPOrEssentialOP,
    annualLimit: [{ currency: Enum.currency.USD, value: 2500000 }],
    startDate: "2023-03-01T00:00:00.000Z",
    endDate: "",
    includedResidence: ["AE-AJ", "AE-FU", "AE-SH", "AE-RK", "AE-UQ", "AE-DU"],
    excludedResidence: ["AE-AZ"],
    coverage: [april.coverages.WorldwideExcludingUSA],
    baseAnnualPremium: [
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.male,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.female,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
    ],
  },
  {
    _id: april.pricingTables.ExtensiveIPOrEliteOP.WorldwideIncludingUSA,
    plan: april.plans.ExtensiveIPOrEliteOP,
    annualLimit: [{ currency: Enum.currency.USD, value: 2500000 }],
    startDate: "2023-03-01T00:00:00.000Z",
    endDate: "",
    includedResidence: ["AE-AJ", "AE-FU", "AE-SH", "AE-RK", "AE-UQ", "AE-DU"],
    excludedResidence: ["AE-AZ"],
    coverage: [april.coverages.WorldwideIncludingUSA],
    baseAnnualPremium: [
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.male,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.female,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
    ],
  },
  {
    _id: april.pricingTables.ExtensiveIPOrEliteOP.WorldwideExcludingUSA,
    plan: april.plans.ExtensiveIPOrEliteOP,
    annualLimit: [{ currency: Enum.currency.USD, value: 2500000 }],
    startDate: "2023-03-01T00:00:00.000Z",
    endDate: "",
    includedResidence: ["AE-AJ", "AE-FU", "AE-SH", "AE-RK", "AE-UQ", "AE-DU"],
    excludedResidence: ["AE-AZ"],
    coverage: [april.coverages.WorldwideExcludingUSA],
    baseAnnualPremium: [
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.male,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.female,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
    ],
  },
  {
    _id: april.pricingTables.EliteIPOrOP.WorldwideIncludingUSA,
    plan: april.plans.EliteIPOrOP,
    annualLimit: [{ currency: Enum.currency.USD, value: 5000000 }],
    startDate: "2023-03-01T00:00:00.000Z",
    endDate: "",
    includedResidence: ["AE-AJ", "AE-FU", "AE-SH", "AE-RK", "AE-UQ", "AE-DU"],
    excludedResidence: ["AE-AZ"],
    coverage: [april.coverages.WorldwideIncludingUSA],
    baseAnnualPremium: [
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.male,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.female,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
    ],
  },
  {
    _id: april.pricingTables.EliteIPOrOP.WorldwideExcludingUSA,
    plan: april.plans.EliteIPOrOP,
    annualLimit: [{ currency: Enum.currency.USD, value: 5000000 }],
    startDate: "2023-03-01T00:00:00.000Z",
    endDate: "",
    includedResidence: ["AE-AJ", "AE-FU", "AE-SH", "AE-RK", "AE-UQ", "AE-DU"],
    excludedResidence: ["AE-AZ"],
    coverage: [april.coverages.WorldwideExcludingUSA],
    baseAnnualPremium: [
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.male,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.female,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
    ],
  },
  {
    _id: april.pricingTables.EliteIPOrEssentialOP.WorldwideIncludingUSA,
    plan: april.plans.EliteIPOrEssentialOP,
    annualLimit: [{ currency: Enum.currency.USD, value: 5000000 }],
    startDate: "2023-03-01T00:00:00.000Z",
    endDate: "",
    includedResidence: ["AE-AJ", "AE-FU", "AE-SH", "AE-RK", "AE-UQ", "AE-DU"],
    excludedResidence: ["AE-AZ"],
    coverage: [april.coverages.WorldwideIncludingUSA],
    baseAnnualPremium: [
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.male,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.female,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
    ],
  },
  {
    _id: april.pricingTables.EliteIPOrEssentialOP.WorldwideExcludingUSA,
    plan: april.plans.EliteIPOrEssentialOP,
    annualLimit: [{ currency: Enum.currency.USD, value: 5000000 }],
    startDate: "2023-03-01T00:00:00.000Z",
    endDate: "",
    includedResidence: ["AE-AJ", "AE-FU", "AE-SH", "AE-RK", "AE-UQ", "AE-DU"],
    excludedResidence: ["AE-AZ"],
    coverage: [april.coverages.WorldwideExcludingUSA],
    baseAnnualPremium: [
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.male,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.female,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
    ],
  },
  {
    _id: april.pricingTables.EliteIPOrExtensiveOP.WorldwideIncludingUSA,
    plan: april.plans.EliteIPOrExtensiveOP,
    annualLimit: [{ currency: Enum.currency.USD, value: 5000000 }],
    startDate: "2023-03-01T00:00:00.000Z",
    endDate: "",
    includedResidence: ["AE-AJ", "AE-FU", "AE-SH", "AE-RK", "AE-UQ", "AE-DU"],
    excludedResidence: ["AE-AZ"],
    coverage: [april.coverages.WorldwideIncludingUSA],
    baseAnnualPremium: [
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.male,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.female,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
    ],
  },
  {
    _id: april.pricingTables.EliteIPOrExtensiveOP.WorldwideExcludingUSA,
    plan: april.plans.EliteIPOrExtensiveOP,
    annualLimit: [{ currency: Enum.currency.USD, value: 5000000 }],
    startDate: "2023-03-01T00:00:00.000Z",
    endDate: "",
    includedResidence: ["AE-AJ", "AE-FU", "AE-SH", "AE-RK", "AE-UQ", "AE-DU"],
    excludedResidence: ["AE-AZ"],
    coverage: [april.coverages.WorldwideExcludingUSA],
    baseAnnualPremium: [
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.male,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
      {
        fromAge: 0,
        toAge: 80,
        gender: Enum.gender.female,
        price: [{ value: 0, currency: Enum.currency.USD }],
      },
    ],
  },
];
module.exports = PricingTable;
